### ISSUE TITLE
NFD.getForwarderStatus() needed

### ISSUE THREAD

**Issue by cawka** [01org/jndn-management#2]
For Android app, we also need to get status information about the forwarder.  Would it be hard to implement equivalent of [NfdForwarderStatus](https://github.com/named-data/ndn-cxx/blob/master/src/management/nfd-forwarder-status.hpp) and `NFD.getForwarderStatus()` command ?

**Comment by abrown** [comment]
Yeah, sounds good.

**Comment by abrown** [comment]
@cawka, what's the ForwarderStatus TLV type? Can't find it in http://redmine.named-data.net/projects/nfd/wiki/ForwarderStatus.

**Comment by cawka** [comment]
There is isn't one (it's directly under content TLV). We should have defined it more clearly on wiki.  Data packet is in the following format

```
{ DataType Length
  { NameType Length {...} }
  { ContentType Length 
    { NfdVersionType Length ... }
    { StartTimestampType Length ... }
    ...
 }
```

**Comment by abrown** [comment]
Thanks

**Comment by abrown** [comment]
@cawka, can you test out https://github.com/01org/jndn-management/pull/4?
